eval $(ssh-agent) &> /dev/null
ssh-add /root/.ssh/id_rsa &> /dev/null

cat <<EOF
Welcome to Jepsen on Docker
===========================

This container runs the Jepsen tests in sub-containers.

To run a test:
   cd jepsen && lein run test -b COMMIT_SHA
EOF

cd /jepsen
