version: '3.7'
x-node:
  &default-node
  build: ./node
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 2.5G
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - AWS_SECURITY_TOKEN
    - AWS_REGION
  env_file:
    - ./secret/node.env
  secrets:
    - authorized_keys
  tty: true
  tmpfs:
    - /run:size=100M
    - /run/lock:size=100M
  volumes:
    - jepsen-shared:/var/jepsen/shared
    - m2:/root/.m2
  networks:
    - jepsen
  privileged: true
  cap_add:
    - ALL
  ports:
    - ${JEPSEN_PORT:-22}

volumes:
  m2:
  jepsen-shared:

secrets:
  authorized_keys:
    file: ./secret/authorized_keys

networks:
  jepsen:

services:
  control:
    container_name: jepsen-control
    hostname: control
    depends_on:
%%DEPS%%
    build: ./control
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN
      - AWS_REGION
    env_file:
      - ./secret/control.env
    privileged: true
    ports:
      - "22"
      - "8080"
    networks:
      - jepsen
    volumes:
      - "jepsen-shared:/var/jepsen/shared"
      - "m2:/root/.m2"
      # Allow running testcontainers on host docker
      - /run/user/${UID:-501}/docker.sock:/var/run/docker.sock
%%DBS%%
